theme: jekyll-theme-merlot
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin
  gem install jekyll-gist jekyll-coffeescript jekyll-assets another-jekyll-plugin
  group :jekyll_plugins do
   gem "jekyll-gist"
   gem "jekyll-coffeescript"
   gem "jekyll-assets"
   gem "another-jekyll-plugin"
 end
